"""replace verification token with otp

Revision ID: c5588205a61f
Revises: c5eb6b3c0430
Create Date: 2026-09-25 21:49:19.116445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5588205a61f'
down_revision = 'c5eb6b3c0430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_otp_hash', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('otp_attempts', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('pending_users_verification_token_hash_key'), type_='unique')
        batch_op.drop_column('verification_token_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('pending_users_verification_token_hash_key'), ['verification_token_hash'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('otp_attempts')
        batch_op.drop_column('verification_otp_hash')

    # ### end Alembic commands ###
